#!/bin/bash

horas=$(date | tr -s " " | cut -f4 -d " " | cut -f1 -d ":")
min=$(date | tr -s " " | cut -f4 -d " " | cut -f2 -d ":")
dia=$(date | tr -s " " | cut -f3 -d " " )
mes=$(date | tr -s " " | cut -f2 -d " " )
anyo=$(date | tr -s " " | cut -f6 -d " " )

echo Son las "$horas" horas, "$min" minutos del día "$dia" de "$mes" de "$anyo"
