#!/bin/bash

#ps aux | tr -s " " | cut -f1 -d " " | tr "\n" " " | sort | uniq
#ps auc | tr -s " " | cut -f1 -d " " | uniq
echo -n -e "USER\tTOTALVSZ"
echo
ps aux | tr -s " " | cut -f1 -d " " | sort | uniq | while read usr;do a=0; if [ $usr != USER ];then echo -n -e "$usr\t"; ps aux | grep ^$usr | tr -s " " | cut -f5 -d " " | while read vsz;do let a=$a+$vsz;echo $a;done|sort -n | tail -1;fi;done
