#!/bin/bash

if [ $# -eq 0 ]
then
	echo Debe introducir las ordenes a implementar
	exit 1
fi
p=0
while [ "$1" != "" ]
do
    $1 &
    pids[$p]=$!
    let p=p+1
    shift
done
echo ${pids[*]}
echo ups
ps
while true
do
	a=$(date | tr -s " " | cut -f4 -d " " | cut -f3 -d ":")
	if [ $a -eq 0 ]
	then
		ps | while read linea
			  do 
			  if echo $linea | grep -q ${pids[*]}
                then fin=$(echo $linea | tr -s " "| cut -f1 -d " ")
		        kill -9 $fin > /dev/null
		        echo "El proceso $fin ha sido matado por espirar su minuto"
              fi
             done
		break
	fi
done 
