#!/bin/bash

if ! echo $1 | grep -x -q "[0-9]\+" 
then
	echo Debes introducir un número
	exit 1
fi
z=-1
let i=$(($1-1))
while [ $i -ge 0 ]
do
	let j=$i
	while [ $j -ge 0 ]
	do
		echo -n " "
		let j=$(($j-1))
	done
	let z=$(($z+2))
	let e=$z
	while [ $e -gt 0 ]
	do
		echo -n "*"
		let e=$(($e-1))
	done
	echo
	let i=$(($i-1))
done

