#!/bin/bash
#10. Cree un shell script llamado bustr, al que se le pase como parámetro una cadena y una lista de 0 a n
#    nombres de fichero. El shell script debe devolvernos los nombres de los archivos que contienen en su
#   interior la cadena especificada. Para evitar errores sólo se hará con los archivos que sean regulares y sobre
#  los que tengamos permiso de lectura. Por ejemplo:
#             bustr cadena fichero1 fichero2 fichero 3
#    devolvería:
#   La cadena "cadena" se ha encontrado en los siguientes ficheros:
#              fichero2
#             fichero3
#¿Cómo podría llamar a bustr para que hiciera la búsqueda en todos los ficheros a partir de un directorio
#dado e incluyendo subdirectorios? Pista bustr cadena ‘....‘

if [ $# -lt 2 ]
then
	echo Error de sintaxis. cadena fich1 fich2 .....
	exit 1
fi
cadena=$1
shift
if test -d "$1"
then
	find $1 -type f -printf "%f\n" | while read fich; do cat $fich | grep -q $cadena; if [ $? -eq 0 ]; then echo $fich;fi;done;
else
	echo
	echo La cadena $1 se ha encontrado en los siguientes ficheros:
	echo
	while test "$1" != ""
	do
		cat $1 | grep -q $cadena
		if [ $? -eq 0 ]
		then
			echo $1
		fi
		shift
	done
fi
