#!/bin/bash

if [ $# -lt 2 ]
then
	echo Error debes introducir un fichero y un directorio. En ese orden
	exit 1
fi
if test -d "$1"
then
	echo El primer parametro debe ser un fichero
	exit 1
fi
if test -f "$2"
then
	echo El segundo parametro debe ser un directorio
	exit 1
fi
cp $1 $2
cd $2
chmod u+x $1
chmod g+x $1
