#!/bin/bash

mils="ls -l"  # Se crea una nueva variable

mils          # No hace nada, buscará el ejecutable  mils, que no existe

$mils         # Ejecutará la orden "ls -l"

echo El contenido de la variables es: $mils
# Muestra el contenido de la variable mils, i.e., "ls -l"


export mils    # Convierte la variable mils en variable de entorno

export var=valor  # Crea la variable, le asigna "valor" y la exporta a la vez

