#!/bin/bash

echo El valor de var1 es ${var1}
# No está definida, no imprimirá nada

echo El valor de la variable es ${var1-5}
# Al no estar definida, le asigna el valor 5

echo El valor es $var1
# Su valor sigue siendo nulo, no se ha definido

