#!/bin/bash

# Programa que imprime el pantalla el contenido de un fichero de datos,
# o el contenido de todos los ficheros de un directorio.

if test -f "$1"
then
       pr $1|less
elif test -d "$1"
then
       cd $1; pr *|less
else
       echo "$1 no es un fichero ni un directorio"
fi

