#!/bin/bash

echo El nombre del programa es $0

echo El primer parámetro recibido es $1

echo El segundo parámetro recibido es $2

echo El tercer parámetro recibido es $3

echo El cuarto parámetro recibido es $4

